<?php

namespace Flowfact\Resources;

/**
 * Class representing ContactType
 *
 *
 * XSD Type: contactType
 */
class ContactType extends ContactShortType
{

    /**
     * This value is ready-only and generated by the server. If the client decides
     *  to set or reset this value during or after the creation of this element, it is
     *  ignored by the server.
     *
     * @property string $identifier
     */
    private $identifier = null;

    /**
     * This item is the parent contact of the given contact. Set this value to null in
     * order
     *  to detach this contact from its parent contact or reset it to a new and valid
     * contact in
     *  the system.
     *
     * @property \Flowfact\Resources\LinkType $parentcontact
     */
    private $parentcontact = null;

    /**
     * Items within this element are linked to this contact by having their
     * "Parent"-Element
     *  set to this adress. There may be more than one linked child contact. You are
     * not able
     *  to set the children by setting these value (which would mean that the parent
     * dsn of
     *  these items would be set to null). In order to release an contact from this
     * parent contact
     *  you have to set the "parentcontact" of the desired contact to null.
     *
     * @property \Flowfact\Resources\LinkType[] $childrencontacts
     */
    private $childrencontacts = null;

    /**
     * @property \Flowfact\Resources\ContactDetailsListType $details
     */
    private $details = null;

    /**
     * @property \Flowfact\Resources\LinkType $inquiries
     */
    private $inquiries = null;

    /**
     * @property string $keyword1
     */
    private $keyword1 = null;

    /**
     * @property string $keyword2
     */
    private $keyword2 = null;

    /**
     * @property \Flowfact\Resources\SalutationType $salutation
     */
    private $salutation = null;

    /**
     * @property string $furtherinfo
     */
    private $furtherinfo = null;

    /**
     * @property string $searchname
     */
    private $searchname = null;

    /**
     * @property \DateTime $birthday
     */
    private $birthday = null;

    /**
     * @property string $skype
     */
    private $skype = null;

    /**
     * @property \Flowfact\Resources\ContactType\PhonenumbersAType $phonenumbers
     */
    private $phonenumbers = null;

    /**
     * @property \Flowfact\Resources\ContactType\EmailaddressesAType $emailaddresses
     */
    private $emailaddresses = null;

    /**
     * @property string $webpage
     */
    private $webpage = null;

    /**
     * @property string $note
     */
    private $note = null;

    /**
     * @property \Flowfact\Resources\BankAccountType $bankaccount
     */
    private $bankaccount = null;

    /**
     * @property boolean $attention
     */
    private $attention = null;

    /**
     * Gets as identifier
     *
     * This value is ready-only and generated by the server. If the client decides
     *  to set or reset this value during or after the creation of this element, it is
     *  ignored by the server.
     *
     * @return string
     */
    public function getIdentifier()
    {
        return $this->identifier;
    }

    /**
     * Sets a new identifier
     *
     * This value is ready-only and generated by the server. If the client decides
     *  to set or reset this value during or after the creation of this element, it is
     *  ignored by the server.
     *
     * @param string $identifier
     * @return self
     */
    public function setIdentifier($identifier)
    {
        $this->identifier = $identifier;
        return $this;
    }

    /**
     * Gets as parentcontact
     *
     * This item is the parent contact of the given contact. Set this value to null in
     * order
     *  to detach this contact from its parent contact or reset it to a new and valid
     * contact in
     *  the system.
     *
     * @return \Flowfact\Resources\LinkType
     */
    public function getParentcontact()
    {
        return $this->parentcontact;
    }

    /**
     * Sets a new parentcontact
     *
     * This item is the parent contact of the given contact. Set this value to null in
     * order
     *  to detach this contact from its parent contact or reset it to a new and valid
     * contact in
     *  the system.
     *
     * @param \Flowfact\Resources\LinkType $parentcontact
     * @return self
     */
    public function setParentcontact(\Flowfact\Resources\LinkType $parentcontact)
    {
        $this->parentcontact = $parentcontact;
        return $this;
    }

    /**
     * Adds as contact
     *
     * Items within this element are linked to this contact by having their
     * "Parent"-Element
     *  set to this adress. There may be more than one linked child contact. You are
     * not able
     *  to set the children by setting these value (which would mean that the parent
     * dsn of
     *  these items would be set to null). In order to release an contact from this
     * parent contact
     *  you have to set the "parentcontact" of the desired contact to null.
     *
     * @return self
     * @param \Flowfact\Resources\LinkType $contact
     */
    public function addToChildrencontacts(\Flowfact\Resources\LinkType $contact)
    {
        $this->childrencontacts[] = $contact;
        return $this;
    }

    /**
     * isset childrencontacts
     *
     * Items within this element are linked to this contact by having their
     * "Parent"-Element
     *  set to this adress. There may be more than one linked child contact. You are
     * not able
     *  to set the children by setting these value (which would mean that the parent
     * dsn of
     *  these items would be set to null). In order to release an contact from this
     * parent contact
     *  you have to set the "parentcontact" of the desired contact to null.
     *
     * @param scalar $index
     * @return boolean
     */
    public function issetChildrencontacts($index)
    {
        return isset($this->childrencontacts[$index]);
    }

    /**
     * unset childrencontacts
     *
     * Items within this element are linked to this contact by having their
     * "Parent"-Element
     *  set to this adress. There may be more than one linked child contact. You are
     * not able
     *  to set the children by setting these value (which would mean that the parent
     * dsn of
     *  these items would be set to null). In order to release an contact from this
     * parent contact
     *  you have to set the "parentcontact" of the desired contact to null.
     *
     * @param scalar $index
     * @return void
     */
    public function unsetChildrencontacts($index)
    {
        unset($this->childrencontacts[$index]);
    }

    /**
     * Gets as childrencontacts
     *
     * Items within this element are linked to this contact by having their
     * "Parent"-Element
     *  set to this adress. There may be more than one linked child contact. You are
     * not able
     *  to set the children by setting these value (which would mean that the parent
     * dsn of
     *  these items would be set to null). In order to release an contact from this
     * parent contact
     *  you have to set the "parentcontact" of the desired contact to null.
     *
     * @return \Flowfact\Resources\LinkType[]
     */
    public function getChildrencontacts()
    {
        return $this->childrencontacts;
    }

    /**
     * Sets a new childrencontacts
     *
     * Items within this element are linked to this contact by having their
     * "Parent"-Element
     *  set to this adress. There may be more than one linked child contact. You are
     * not able
     *  to set the children by setting these value (which would mean that the parent
     * dsn of
     *  these items would be set to null). In order to release an contact from this
     * parent contact
     *  you have to set the "parentcontact" of the desired contact to null.
     *
     * @param \Flowfact\Resources\LinkType[] $childrencontacts
     * @return self
     */
    public function setChildrencontacts(array $childrencontacts)
    {
        $this->childrencontacts = $childrencontacts;
        return $this;
    }

    /**
     * Gets as details
     *
     * @return \Flowfact\Resources\ContactDetailsListType
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * Sets a new details
     *
     * @param \Flowfact\Resources\ContactDetailsListType $details
     * @return self
     */
    public function setDetails(\Flowfact\Resources\ContactDetailsListType $details)
    {
        $this->details = $details;
        return $this;
    }

    /**
     * Gets as inquiries
     *
     * @return \Flowfact\Resources\LinkType
     */
    public function getInquiries()
    {
        return $this->inquiries;
    }

    /**
     * Sets a new inquiries
     *
     * @param \Flowfact\Resources\LinkType $inquiries
     * @return self
     */
    public function setInquiries(\Flowfact\Resources\LinkType $inquiries)
    {
        $this->inquiries = $inquiries;
        return $this;
    }

    /**
     * Gets as keyword1
     *
     * @return string
     */
    public function getKeyword1()
    {
        return $this->keyword1;
    }

    /**
     * Sets a new keyword1
     *
     * @param string $keyword1
     * @return self
     */
    public function setKeyword1($keyword1)
    {
        $this->keyword1 = $keyword1;
        return $this;
    }

    /**
     * Gets as keyword2
     *
     * @return string
     */
    public function getKeyword2()
    {
        return $this->keyword2;
    }

    /**
     * Sets a new keyword2
     *
     * @param string $keyword2
     * @return self
     */
    public function setKeyword2($keyword2)
    {
        $this->keyword2 = $keyword2;
        return $this;
    }

    /**
     * Gets as salutation
     *
     * @return \Flowfact\Resources\SalutationType
     */
    public function getSalutation()
    {
        return $this->salutation;
    }

    /**
     * Sets a new salutation
     *
     * @param \Flowfact\Resources\SalutationType $salutation
     * @return self
     */
    public function setSalutation(\Flowfact\Resources\SalutationType $salutation)
    {
        $this->salutation = $salutation;
        return $this;
    }

    /**
     * Gets as furtherinfo
     *
     * @return string
     */
    public function getFurtherinfo()
    {
        return $this->furtherinfo;
    }

    /**
     * Sets a new furtherinfo
     *
     * @param string $furtherinfo
     * @return self
     */
    public function setFurtherinfo($furtherinfo)
    {
        $this->furtherinfo = $furtherinfo;
        return $this;
    }

    /**
     * Gets as searchname
     *
     * @return string
     */
    public function getSearchname()
    {
        return $this->searchname;
    }

    /**
     * Sets a new searchname
     *
     * @param string $searchname
     * @return self
     */
    public function setSearchname($searchname)
    {
        $this->searchname = $searchname;
        return $this;
    }

    /**
     * Gets as birthday
     *
     * @return \DateTime
     */
    public function getBirthday()
    {
        return $this->birthday;
    }

    /**
     * Sets a new birthday
     *
     * @param \DateTime $birthday
     * @return self
     */
    public function setBirthday(\DateTime $birthday)
    {
        $this->birthday = $birthday;
        return $this;
    }

    /**
     * Gets as skype
     *
     * @return string
     */
    public function getSkype()
    {
        return $this->skype;
    }

    /**
     * Sets a new skype
     *
     * @param string $skype
     * @return self
     */
    public function setSkype($skype)
    {
        $this->skype = $skype;
        return $this;
    }

    /**
     * Gets as phonenumbers
     *
     * @return \Flowfact\Resources\ContactType\PhonenumbersAType
     */
    public function getPhonenumbers()
    {
        return $this->phonenumbers;
    }

    /**
     * Sets a new phonenumbers
     *
     * @param \Flowfact\Resources\ContactType\PhonenumbersAType $phonenumbers
     * @return self
     */
    public function setPhonenumbers(\Flowfact\Resources\ContactType\PhonenumbersAType $phonenumbers)
    {
        $this->phonenumbers = $phonenumbers;
        return $this;
    }

    /**
     * Gets as emailaddresses
     *
     * @return \Flowfact\Resources\ContactType\EmailaddressesAType
     */
    public function getEmailaddresses()
    {
        return $this->emailaddresses;
    }

    /**
     * Sets a new emailaddresses
     *
     * @param \Flowfact\Resources\ContactType\EmailaddressesAType $emailaddresses
     * @return self
     */
    public function setEmailaddresses(\Flowfact\Resources\ContactType\EmailaddressesAType $emailaddresses)
    {
        $this->emailaddresses = $emailaddresses;
        return $this;
    }

    /**
     * Gets as webpage
     *
     * @return string
     */
    public function getWebpage()
    {
        return $this->webpage;
    }

    /**
     * Sets a new webpage
     *
     * @param string $webpage
     * @return self
     */
    public function setWebpage($webpage)
    {
        $this->webpage = $webpage;
        return $this;
    }

    /**
     * Gets as note
     *
     * @return string
     */
    public function getNote()
    {
        return $this->note;
    }

    /**
     * Sets a new note
     *
     * @param string $note
     * @return self
     */
    public function setNote($note)
    {
        $this->note = $note;
        return $this;
    }

    /**
     * Gets as bankaccount
     *
     * @return \Flowfact\Resources\BankAccountType
     */
    public function getBankaccount()
    {
        return $this->bankaccount;
    }

    /**
     * Sets a new bankaccount
     *
     * @param \Flowfact\Resources\BankAccountType $bankaccount
     * @return self
     */
    public function setBankaccount(\Flowfact\Resources\BankAccountType $bankaccount)
    {
        $this->bankaccount = $bankaccount;
        return $this;
    }

    /**
     * Gets as attention
     *
     * @return boolean
     */
    public function getAttention()
    {
        return $this->attention;
    }

    /**
     * Sets a new attention
     *
     * @param boolean $attention
     * @return self
     */
    public function setAttention($attention)
    {
        $this->attention = $attention;
        return $this;
    }


}

