<?php

namespace Flowfact\Resources;

/**
 * Class representing UserShortType
 *
 *
 * XSD Type: userShortType
 */
class UserShortType extends LinkType
{

    /**
     * This value is ready-only and generated by the server. If the client decides
     *  to set or reset this value during or after the creation of this element, it is
     *  ignored by the server.
     *
     * @property string $id
     */
    private $id = null;

    /**
     * @property string $identifier
     */
    private $identifier = null;

    /**
     * @property string $internaldescription
     */
    private $internaldescription = null;

    /**
     * @property string $keyword
     */
    private $keyword = null;

    /**
     * @property string $headline
     */
    private $headline = null;

    /**
     * @property \Flowfact\Resources\LocationType $location
     */
    private $location = null;

    /**
     * This characteristics are the preselected characteristics for this
     *  user (STD_MKM).
     *
     * @property \Flowfact\Resources\CharacteristicsUrlType $characteristics
     */
    private $characteristics = null;

    /**
     * Gets as id
     *
     * This value is ready-only and generated by the server. If the client decides
     *  to set or reset this value during or after the creation of this element, it is
     *  ignored by the server.
     *
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets a new id
     *
     * This value is ready-only and generated by the server. If the client decides
     *  to set or reset this value during or after the creation of this element, it is
     *  ignored by the server.
     *
     * @param string $id
     * @return self
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * Gets as identifier
     *
     * @return string
     */
    public function getIdentifier()
    {
        return $this->identifier;
    }

    /**
     * Sets a new identifier
     *
     * @param string $identifier
     * @return self
     */
    public function setIdentifier($identifier)
    {
        $this->identifier = $identifier;
        return $this;
    }

    /**
     * Gets as internaldescription
     *
     * @return string
     */
    public function getInternaldescription()
    {
        return $this->internaldescription;
    }

    /**
     * Sets a new internaldescription
     *
     * @param string $internaldescription
     * @return self
     */
    public function setInternaldescription($internaldescription)
    {
        $this->internaldescription = $internaldescription;
        return $this;
    }

    /**
     * Gets as keyword
     *
     * @return string
     */
    public function getKeyword()
    {
        return $this->keyword;
    }

    /**
     * Sets a new keyword
     *
     * @param string $keyword
     * @return self
     */
    public function setKeyword($keyword)
    {
        $this->keyword = $keyword;
        return $this;
    }

    /**
     * Gets as headline
     *
     * @return string
     */
    public function getHeadline()
    {
        return $this->headline;
    }

    /**
     * Sets a new headline
     *
     * @param string $headline
     * @return self
     */
    public function setHeadline($headline)
    {
        $this->headline = $headline;
        return $this;
    }

    /**
     * Gets as location
     *
     * @return \Flowfact\Resources\LocationType
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Sets a new location
     *
     * @param \Flowfact\Resources\LocationType $location
     * @return self
     */
    public function setLocation(\Flowfact\Resources\LocationType $location)
    {
        $this->location = $location;
        return $this;
    }

    /**
     * Gets as characteristics
     *
     * This characteristics are the preselected characteristics for this
     *  user (STD_MKM).
     *
     * @return \Flowfact\Resources\CharacteristicsUrlType
     */
    public function getCharacteristics()
    {
        return $this->characteristics;
    }

    /**
     * Sets a new characteristics
     *
     * This characteristics are the preselected characteristics for this
     *  user (STD_MKM).
     *
     * @param \Flowfact\Resources\CharacteristicsUrlType $characteristics
     * @return self
     */
    public function setCharacteristics(\Flowfact\Resources\CharacteristicsUrlType $characteristics)
    {
        $this->characteristics = $characteristics;
        return $this;
    }


}

